#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
  
  # possibly add something here to ensure iTerm2 is installed using Homebrew
  # cask like in the previous example

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi

  zsh -ic 'fast-theme XDG:loskir'

  chsh -s /opt/homebrew/bin/fish
fi
